# CONFIGURACION DEL SERVIDOR
spring.application.name=Mars Rover API
server.port=${PORT:8080}
server.servlet.context-path=/

# CONFIGURACION DE LA BASE DE DATOS
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURACION DE HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# CONFIGURACION DE LA API
app.map.width=${MAP_WIDTH:7}
app.map.height=${MAP_HEIGHT:6}